CREATE DATABASE DB_DURE
GO
USE DB_DURE
GO

CREATE TABLE ESPECIALIDADES(
  IDESPECIALIDAD INT NOT NULL PRIMARY KEY IDENTITY (1,1),
  DESCRIPCION VARCHAR(50) NOT NULL
)
GO
DROP TABLE MEDICOS
CREATE TABLE MEDICOS(
  IDMEDICO INT NOT NULL PRIMARY KEY IDENTITY (1,1),
  IDESPECIALIDAD INT NOT NULL FOREIGN KEY REFERENCES ESPECIALIDADES (IDESPECIALIDAD),
  APELLIDO VARCHAR(50) NULL,
  NOMBRE VARCHAR(50) NULL,
  SEXO CHAR(1)  NULL CHECK (SEXO IN ('M', 'F')),
  FECHANAC DATE NULL,
  DNI VARCHAR(50) NULL UNIQUE,
  NMATRICULA VARCHAR (50) NULL UNIQUE,
  EMAIL VARCHAR(100) NULL,
  TELEFONO VARCHAR(50) NULL,
  TIPOTEL VARCHAR(50) NULL,
  FECHAINGRESO DATE NULL,
  DIRECCION VARCHAR(100)  NULL,
  CP INT NULL,
  LOCALIDAD VARCHAR(50) NULL,
  PROVINCIA VARCHAR (50) NULL,
  ESTADO BIT NULL DEFAULT 1
)

SET DATEFORMAT 'DMY'
/* ESPECIALIDADES */
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'MÉDICO CLÍNICO')
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'CARDIOLOGÍA')
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'GASTROENTEROLOGÍA')
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'PEDIATRÍA')
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'CIRUJANO PLASTICO')
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'NEUROCIRUJANO')
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'GINECOLOGO')
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'NUTRICIONISTA')
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'OFTALMOLOGO')

/* MEDICOS */
INSERT INTO MEDICOS([NOMBRE],[APELLIDO],[DNI],[FECHANAC],[IDESPECIALIDAD],[SEXO],[NMATRICULA],[EMAIL],[TELEFONO],[TIPOTEL],[DIRECCION],
[CP],[LOCALIDAD],[PROVINCIA],[ESTADO],[FECHAINGRESO])
VALUES ('April','Kepner','332571','07/11/2016',5,'M','124578','daniela.dure@escandinavia.com','01136588201','Celular','Zapiola 4210',
1665,'Jose.c.Paz','Buenos Aires',1,'05/10/2010'),(8,'Liberty','Wilson','F"','23/02/70',176934,5888,'accumsan@adipiscing.com','0981991','CASA','15/05/13','471-3114 Vulputate, Av.','5569','Dos Hermanas','Moldova',1),
(3,'Raja','Avila','"M','10/11/60',312260,8550,'sem@pede.edu','02928468','CELULAR','04/04/11','340-5034 Leo. St.','80556','Saint-Servais','Panama',1)


/*PROCEDURES*/

create procedure modificarmedico
@Nombre varchar(50),
@Apellido varchar(50),
@id int
as
update MEDICOS set
NOMBRE = @Nombre, APELLIDO = @Apellido Where IDMEDICO = @id

exec modificarmedico 'Jesus','Angel', 9