CREATE DATABASE DURE_DB
GO
USE DURE_DB
GO


CREATE TABLE ESPECIALIDADES(
  IDESPECIALIDAD INT NOT NULL PRIMARY KEY IDENTITY (1,1),
  DESCRIPCION VARCHAR(50) NOT NULL
)
GO
CREATE TABLE MEDICOS(
  IDMEDICO BIGINT NOT NULL PRIMARY KEY,
  IDESPECIALIDAD INT NOT NULL FOREIGN KEY REFERENCES ESPECIALIDADES (IDESPECIALIDAD),
  FECHAINGRESO DATE NOT NULL
)
SET DATEFORMAT 'DMY'
/* ESPECIALIDADES */
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'MÉDICO CLÍNICO')
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'CARDIOLOGÍA')
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'GASTROENTEROLOGÍA')
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'PEDIATRÍA')
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'ENDOCRINOLOGÍA')
INSERT INTO ESPECIALIDADES ( DESCRIPCION) VALUES ( 'ODONTOLOGÍA')

/* MEDICOS */
INSERT INTO MEDICOS([IDMEDICO],[FECHAINGRESO],[IDESPECIALIDAD]) VALUES(1,'11/05/2011',1),
(2,'18/05/2001',5),
(3,'09/11/2009',2),
(4,'18/12/1985',4),
(5,'07/12/2016',6)

select M.IDMEDICO,E.IDESPECIALIDAD,E.Descripcion  From MEDICOS M, ESPECIALIDADES E Where M.IDESPECIALIDAD=E.IDESPECIALIDAD

Select Idespecialidad, Descripcion from Especialidades